language: python
python:
  - 2.7
install:
  - "pip install -e git://github.com/edx/xblock-sdk.git@v0.1.2#egg=xblock-sdk==v0.1.2"
  - pip install -r flow_control/requirements/base.txt
  - pip install -r flow_control/requirements/test.txt
  - pip install -r requirements.txt
script:
  - pep8 flow_control --max-line-length=120
  # - pylint flow_control
  - DJANGO_SETTINGS_MODULE="workbench.settings" nosetests

notifications:
  email: false
